timezone: "UTC"
markdown: kramdown

# Site configuration
title: "Conferencias Tech España"
description: "Los próximos eventos tecnológicos más relevantes de España"
url: "https://conferencias-tech-espana.github.io"
baseurl: ""

# Google Analytics
google_analytics: "G-077BBT8NE3"

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  conferences:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

  - SETUP.md
  - setup.sh
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.gemspec"
