timezone: "UTC"
markdown: kramdown

# Site configuration
title: "TechConf by Chimichurri Code"
description: "Los pr칩ximos eventos tecnol칩gicos m치s relevantes de Espa침a"
url: "https://conferencias-tech-espana.github.io"
baseurl: ""

# Google Analytics
google_analytics: "G-077BBT8NE3"

# Google Maps API Keys
google_maps_api_key: "AIzaSyAj88BlU6RkgiNfm0Cfg0MqUGv-g8P6Bmc"
google_maps_api_key_dev: "AIzaSyAj88BlU6RkgiNfm0Cfg0MqUGv-g8P6Bmc"  # Misma key por ahora

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  conferences:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SETUP.md
  - MAPS_SETUP.md
  - setup.sh
  - serve-dev.sh
  - _config_dev.yml
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.gemspec"
